server {
    listen 80;
    server_name _;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://localhost:10000/api/;
        proxy_set_header Host $host;
    }

    # MUHIM: /docs va /openapi.json manzillarini backendga yo'naltirish
    location /docs {
        proxy_pass http://localhost:10000/docs;
        proxy_set_header Host $host;
    }

    location /openapi.json {
        proxy_pass http://localhost:10000/openapi.json;
        proxy_set_header Host $host;
    }

    location = /healthz {
        return 200 'ok';
        add_header Content-Type text/plain;
    }
}